### ISSUE TITLE
Subword delete works in wrong buffer

### ISSUE THREAD

**Issue by eviljoe** [dsandstrom/atom-subword-navigation#15]
The subword delete left/right don't always act on the text that I am currently working with.  When I have a popup dialog open, they will still work on the bottom window instead of the dialog.

To Recreate:
 1. Open a file that contains some text
 1. Open the file symbols dialog
 1. Type anything into file symbols filter
 1. Attempt a subword delete left
  * The subword delete will act on the original file's buffer instead of the dialog's filter

The following is how I have my keys mapped:
```cson
'.platform-linux atom-text-editor, .platform-win32 atom-text-editor':
    'ctrl-backspace': 'subword-navigation:delete-left'
    'ctrl-delete': 'subword-navigation:delete-right'
```

Side Note: I have also noticed that subword navigation does not work in dialogs, but it doesn't affect my cursor position in the bottom window.

**Comment by dsandstrom** [comment]
Thanks for the excellent bug report, however this is a known problem.  See #4.  I have tried to fix this, but I can't get it to work.  Here is what I tried: https://github.com/atom/find-and-replace/issues/287.  If you can point out a package that is able to have a command run outside of the normal text editor, than point me to it.  I will try to reproduce.

**Comment by eviljoe** [comment]
I looked into this for a few hours and come to the conclusion that this is an unfortunate API shortcoming.  Well, if you are aware of the issue and already have a ticket for it, I guess you can close this out.

PS: I love this the subword navigation package, and really think it is essential to make Atom usable.  Keep up the good work!

**Comment by eviljoe** [comment]
Months later... I found a workaround!  Updating the keybindings to be active based on the `atom-text-editor:not([mini])` class prevents subword-navigation from activating while not in the main text editor buffer.

Here is how my subword-navigation key mappings look:

```cson
'.platform-linux atom-text-editor:not([mini]), .platform-win32 atom-text-editor:not([mini])':
    'ctrl-left': 'subword-navigation:move-left'
    'ctrl-right': 'subword-navigation:move-right'
    'ctrl-shift-left': 'subword-navigation:select-left'
    'ctrl-shift-right': 'subword-navigation:select-right'
    'ctrl-backspace': 'subword-navigation:delete-left'
    'ctrl-delete': 'subword-navigation:delete-right'
```

I saw this use of the `mini` class by a ton of the core commands (ex/ editor:toggle-line-comments).

This is not an ideal solution.  I would still LOVE to use subword navigation in the popup dialogs (like the fuzzy-finder), but at least this prevents me constantly deleting text from the wrong buffer.

**Comment by dsandstrom** [comment]
Good find.  Mind submitting a PR?

**Comment by eviljoe** [comment]
Sure, give me a day or two.

**Comment by dsandstrom** [comment]
Keymaps have been merged.  But, I would still like to be able to use subword navigation in mini editors.

**Comment by dsandstrom** [comment]
This package's functionality has been merged into core.  And even better news, it works in mini editors, too.  Can't wait for the next Atom release.

**Comment by dsandstrom** [comment]
no longer maintained
