### ISSUE TITLE
Norwegian characters (æ, ø, å) should not break words

### ISSUE THREAD

**Issue by KnutHelland** [dsandstrom/atom-subword-navigation#19]
Thanks for a good plugin!

I would love to have the norwegian characters æ, ø, and å to be treated like other characters. It would probably be an idea to make this configurable as `subword-navigation.additionalWordCharacters`?

**Comment by dsandstrom** [comment]
Thanks for bringing this up.  I will see if I can add them (along with Swedish characters).  I don't think a config is necessary.

**Comment by dsandstrom** [comment]
Linking this for future reference: https://en.wikipedia.org/wiki/Latin-1_Supplement_%28Unicode_block%29
